### ISSUE TITLE
Error when running EndToEndTest.php unit test

### ISSUE THREAD

**Issue by stanley-cheung** [thinkerou/grpc-php7#2]
Hi, thanks for the contribution. I was trying to look into this and ran into an issue. I took your branch, and the latest grpc master branch, and tried to compile this with PHP 7. I got around some fairly minor issue here and there but was stuck trying to debug this one:

So I was trying to run the unit tests via `bin/run_tests.sh`. Some of the simpler tests run correctly, like `TimevalTest.php`, `CallTest.php`, `ServerTest.php`. But `EndToEndTest.php` failed. Here's the error I got

```
E0715 19:24:24.681174835   31243 compression.c:157]          Unknown compression level 32643
./bin/run_tests.sh: line 41: 31243 Aborted                 php $extension_dir -d max_execution_time\
=300 $(which phpunit) -v --debug ../$1
```

That's because of this: https://github.com/grpc/grpc/blob/master/src/core/lib/compression/compression.c#L157

And I think that's because somehow this `is_set` is true, which should not:
https://github.com/grpc/grpc/blob/master/src/core/lib/surface/call.c#L1414

The error originates from this `Grpc\OP_SEND_STATUS_FROM_SERVER` array being set to something non-trivial. 
https://github.com/grpc/grpc/blob/master/src/php/tests/unit_tests/EndToEndTest.php#L72

My guess is that somewhere in here: https://github.com/thinkerou/grpc-php7/blob/master/ext/grpc/call.c#L369 there's some leak setting up the internal metadata array.

Can you please look into it? Thanks

**Comment by stanley-cheung** [comment]
Figured it out. There should be a line

```
memset(ops, 0, sizeof(ops));
```

around here: https://github.com/thinkerou/grpc-php7/blob/master/ext/grpc/call.c#L299

**Comment by stanley-cheung** [comment]
Now I am running into segfault in `CallTest.php`

```
Starting test 'CallTest::testAddEmptyMetadata'.
./bin/run_tests.sh: line 41: 20195 Segmentation fault      php $extension_dir -d max_execution_time\
=300 $(which phpunit) -v --debug ../$1
```

**Comment by stanley-cheung** [comment]
The segfault seems to come from this `grpc_channel_create_call`: https://github.com/thinkerou/grpc-php7/blob/master/ext/grpc/call.c#L253

**Comment by stanley-cheung** [comment]
Nevermind, my fault. Now all unit tests run successfully. Let me review the code more closely now.

**Comment by thinkerou** [comment]
Ohhh, really lack a line: `memset(ops, 0, sizeof(ops));`  https://github.com/thinkerou/grpc-php7/blob/master/ext/grpc/call.c#L299
Thanks @stanley-cheung , I have added it.

**Comment by stanley-cheung** [comment]
I believe for this line: https://github.com/thinkerou/grpc-php7/blob/master/ext/grpc/call.c#L255, the value for `host_override` needs to be `host_override == NULL ? NULL : ZSTR_VAL(host_override)`

**Comment by thinkerou** [comment]
Yeth, If str is null when calls `ZSTR_VAL(str)`, this will crash. So, you are right.
